### ISSUE TITLE
Migration from version 1.0.2 to 2.1.3

### ISSUE THREAD

**Issue by jaimepineiro** [ontimize/ontimize-jee#16]
We have an application with ontimize-jee version 1.0.2 we would like to migrate to latest version. I've checked in imatia artifactory but there is not deployed version  higher than 2.0.0. 
https://artifactory.imatia.com/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/com/ontimize/jee/ontimize-jee
I've also checked [release notes](https://www.ontimize.com/xwiki/bin/view/Ontimize+EE/Release+Notes+Ontimize+EE) but there is not entry for version more recent that 1.0.2
Is 2.1.3 version stable? Can i do this migration?

**Comment by pmkirsten** [comment]
All new versions (release or snapshot) are now deployed to Maven Central.As of today, the latest stable version is 5.5.0: https://search.maven.org/artifact/com.ontimize.jee/ontimize-jee/5.5.0/pom
